name: CI Publication
on:
  push:
    branches:
      - master

jobs:

  versioning:
    name: Generate versioning file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      name: Set up JDK
      with:
        java-version: 11
    - name: Make gradle executable
      run: chmod +x gradlew
    - name: Publish
      id: gradle
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: generateProjectVersionFile
      env:
        VERSIONING_FILE_PATH: ~/versioning_file.txt
    - uses: actions/upload-artifact@v2
      name: Upload version for publication
      with:
        name: versioning_file
        path: ~/versioning_file.txt

  deploy:
    needs: [versioning]
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-latest
    name: Publish artifacts
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decrypt private key
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SIGNING_PASSWORD}}" --output secring.txt secring.txt.gpg
      - name: Make gradle executable
        run: chmod +x gradlew
      - uses: actions/download-artifact@v2
        name: Download version from publication
        with:
          name: versioning_file
      - name: Publish
        id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishAllPublicationsToGitHubPackagesRepository
        env:
          VERSIONING_FILE_PATH: ~/versioning_file.txt
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          SIGNING_PUBLIC_KEY_ID: ${{secrets.SIGNING_PUBLIC_KEY_ID}}
          SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
